### PR TITLE
Adds a layer to display location-based groups

### PR DESCRIPTION
**Pull request by rafmudaf**
This pull request adds a layer to the map to display RSE groups tied to a location (city or region) as described in https://github.com/USRSE/usrse.github.io/pull/876.

Screen Shot 2022-08-09 at 3 21 33 PM

### CODE REVIEW

**Comment by cosden** [comment]
@rafmudaf Looks great! I just pulled it down and previewed locally. It looks slick and I love that clicking on the regional group brings you straight to the slack channel. The colors and marker size all look great. Nice job! Sorry it took so long for me to get to it.

I'm been trying to think of any issues, and I have one potential concern that maybe we can brainstorm together as to how to resolve it. In presentations I often show the membership map to visually show "where our members are located" and the change over time. It would be great to have the ability to toggle the regional groups on and off to be consistent. Outside of that (which seems like a lot of work), should we just have a separate page that only insiders know where it is? 
Any other ideas?

**Comment by danielskatz** [comment]
maybe I shouldn't have merged the post PR without this one...

**Comment by danielskatz** [comment]
@cosden - I think we should merge this now, then address your issue above following that.  If you agree, maybe go ahead and merge it

**Comment by cosden** [comment]
Yes, I agree. Let's merge. We can worry about this later. I'll open an issue to keep track of it. Honestly, it might only be me that cares about it, and I'm happy to have a page that isn't linked from anywhere that does this.

**Review by cosden — APPROVED** [review]

**Pull request merged**
